### ISSUE TITLE
Fix Requirements.txt File

### ISSUE THREAD

**Issue by arhamshah** [arhamshah/SolubilityPrediction#1]
Current Requirements.txt has many dependencies which are not related to this project. 
**In order to resolve this issue:-** Update Requirements.txt with dependencies required by this application, don't forget to include rdkit dependency.

**Comment by ShrutiKatpara** [comment]
Hey, @arhamshah. Maybe I'll give a try. Thanks!

**Comment by arhamshah** [comment]
Fixed Requirements.txt
